## ----------------------------------------------------------------------------
## nexus | GanESS.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays in the GanESS detector.
##
## The GanESS Group
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
#/Geometry/GanESS/elfield false
#/Geometry/GanESS/max_step_size 1. mm

##### GENERATOR #####
/Generator/IonGenerator/atomic_number 83
/Generator/IonGenerator/mass_number 214
/Generator/IonGenerator/region VESSEL

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 0.6 MeV
/Actions/DefaultEventAction/max_energy 2.55 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### PERSISTENCY #####
/nexus/persistency/output_file GanESS_run3
#/nexus/persistency/output_file test

## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type background