DROP TABLE IF EXISTS `DetectorGeo`;
CREATE TABLE `DetectorGeo` (
	  `XMIN` float NOT NULL COMMENT 'MINIMUM X VALUE (mm)',
	  `XMAX` float NOT NULL COMMENT 'MAXIMUM X VALUE (mm)',
	  `YMIN` float NOT NULL COMMENT 'MINIMUM Y VALUE (mm)',
	  `YMAX` float NOT NULL COMMENT 'MAXIMUM Y VALUE (mm)',
	  `ZMIN` float NOT NULL COMMENT 'MINIMUM Z VALUE (mm)',
	  `ZMAX` float NOT NULL COMMENT 'MAXIMUM Z VALUE (mm)',
	  `RMAX` float NOT NULL COMMENT 'MAXIMUM RADIUS (mm)'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `DetectorGeo` VALUES (-80, 80, -80, 80, 0, 300, 80);
